import { XCommand, XSchema } from '../Contracts/Generic'

const APIs: { [K in XCommand]: XSchema[] } = {
    subaccount: [
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/subaccount',
            method: 'PUT',
            params: [],
            description: 'Update a subaccount',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/subaccount/{id}',
            method: 'GET',
            params: [
                {
                    parameter: 'id',
                    required: true,
                    type: 'String',
                    description: 'The ID of the subaccount to fetch',
                    paramType: 'path',
                }
            ],
            description: 'Fetch a specific subaccount',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/subaccount',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'List all sub accounts created on your integration ',
        },
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/subaccount',
            method: 'POST',
            params: [
                {
                    parameter: 'business_name',
                    required: true,
                    type: 'String',
                    description: 'Name of business for subaccount',
                },
                {
                    parameter: 'settlement_bank',
                    required: true,
                    type: 'String',
                    description: 'Bank code (see List Banks endpoint for accepted codes)',
                },
                {
                    parameter: 'account_number',
                    required: true,
                    type: 'String',
                    description: 'NUBAN bank account number',
                },
                {
                    parameter: 'percentage_charge',
                    required: true,
                    type: 'String',
                    description: 'Default percentage charged when receiving on behalf of this subaccount',
                },
                {
                    parameter: 'primary_contact_email',
                    required: false,
                    type: 'String',
                    description: 'Contact email for the subaccount',
                },
                {
                    parameter: 'primary_contact_name',
                    required: false,
                    type: 'String',
                    description: 'Contact person name for this subaccount',
                },
                {
                    parameter: 'primary_contact_phone',
                    required: false,
                    type: 'String',
                    description: 'Contact phone number for this subaccount',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional information in structured JSON format',
                },
                {
                    parameter: 'settlement_schedule',
                    required: false,
                    type: 'String',
                    description: 'Settlement schedule: "auto" (T+1), "weekly", "monthly", or "manual"',
                },
            ],
            description: 'Create a new subaccount',
        },
    ],
    page: [
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/page/',
            method: 'PUT',
            params: [
                {
                    parameter: 'name',
                    required: false,
                    type: 'String',
                    description: 'Name of page',
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Short description of page',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount to be charged in kobo. Will override the amount for existing subscriptions',
                },
                {
                    parameter: 'active',
                    required: false,
                    type: 'String',
                    description: 'Set to false to deactivate page url',
                },
            ],
            description: 'Update a payment page',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/page/id_or_plan_code',
            method: 'GET',
            params: [],
            description: 'Fetch a specific payment page',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/page',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
                {
                    parameter: 'interval',
                    required: false,
                    type: 'String',
                    description: 'Filter list by plans with specified interval',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Filter list by plans with specified amount (in kobo)',
                },
            ],
            description: 'List all payment pages',
        },
        {
            api: 'check',
            endpoint: 'https://api.paystack.co/page/check_slug_availability/slug',
            method: 'GET',
            params: [
                {
                    parameter: 'slug',
                    required: true,
                    type: 'String',
                    description: 'URL slug to be confirmed',
                },
            ],
            description: 'Check if a page slug is available',
        },
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/page',
            method: 'POST',
            params: [
                {
                    parameter: 'name',
                    required: true,
                    type: 'String',
                    description: 'Name of page',
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Short description of page',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Default amount to accept using this page (leave empty for donations)',
                },
                {
                    parameter: 'slug',
                    required: false,
                    type: 'String',
                    description: 'URL slug for the page (page will be accessible at https://paystack.com/pay/[slug])',
                },
                {
                    parameter: 'redirect_url',
                    required: false,
                    type: 'String',
                    description: 'URL to redirect to upon successful payment',
                },
                {
                    parameter: 'send_invoices',
                    required: false,
                    type: 'String',
                    description: 'Set to false to disable invoice emails',
                },
                {
                    parameter: 'custom_fields',
                    required: false,
                    type: 'String',
                    description: 'Custom fields to accept (see documentation for format)',
                },
            ],
            description: 'Create a new payment page',
        },
    ],
    transfer: [
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/transfer',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'List all transfers',
        },
        {
            api: 'finalize',
            endpoint: 'https://api.paystack.co/transfer/finalize_transfer',
            method: 'POST',
            params: [
                {
                    parameter: 'transfer_code',
                    required: true,
                    type: 'String',
                    description: 'Transfer code',
                },
                {
                    parameter: 'otp',
                    required: true,
                    type: 'String',
                    description: 'OTP sent to business phone to verify transfer',
                },
            ],
            description: 'Finalize a transfer by confirming OTP',
        },
        {
            api: 'initiate',
            endpoint: 'https://api.paystack.co/transfer',
            method: 'POST',
            params: [
                {
                    parameter: 'source',
                    required: true,
                    type: 'String',
                    description: 'Where should we transfer from? Only [balance] for now',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount to transfer in kobo',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Specify the currency of the transfer. Defaults to NGN',
                    default: 'NGN',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'reason',
                    required: false,
                    type: 'String',
                    description: 'The reason for the transfer.',
                },
                {
                    parameter: 'recipient',
                    required: true,
                    type: 'String',
                    description: 'Code for transfer recipient.',
                },
                {
                    parameter: 'reference',
                    required: false,
                    type: 'String',
                    description: 'If specified, the field should be a unique identifier (in lowercase) for the object. Only `-` `,` `_` and alphanumeric characters allowed.',
                },
                {
                    parameter: 'account_reference',
                    required: false,
                    type: 'String',
                    description: 'A unique identifier required in Kenya for MPESA Paybill and Till transfers.',
                },
            ],
            description: 'Send money to your customers. Status of transfer object returned will be [pending] if OTP is disabled. In the event that an OTP is required, status will read [otp].',
        },
        {
            api: 'verify',
            endpoint: 'https://api.paystack.co/transfer/{reference}',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Transfer reference to verify',
                    paramType: 'path',
                },
            ],
            description: 'Verify transfer status by reference',
        },
        {
            api: 'disable',
            endpoint: 'https://api.paystack.co/transfer/disable_otp',
            method: 'POST',
            params: [],
            description: 'Disable OTP requirement for transfers',
        },
        {
            api: 'enable',
            endpoint: 'https://api.paystack.co/transfer/enable_otp',
            method: 'POST',
            params: [],
            description: 'Enable OTP requirement for transfers',
        },
        {
            api: 'initiate',
            endpoint: 'https://api.paystack.co/transfer/bulk',
            method: 'POST',
            params: [
                {
                    parameter: 'source',
                    required: false,
                    type: 'String',
                    description: 'Where should we transfer from? Only [balance] for now',
                },
                {
                    parameter: 'transfers',
                    required: true,
                    type: 'Array',
                    description: 'A list of transfer object..',
                },
            ],
            description: 'Batch multiple transfers in a single request. You need to disable the Transfers OTP requirement to use this endpoint.',
        },
        {
            api: 'finalize',
            endpoint: 'https://api.paystack.co/transfer/disable_otp_finalize',
            method: 'POST',
            params: [
                {
                    parameter: 'otp',
                    required: true,
                    type: 'String',
                    description: 'OTP sent to business phone to verify disabling OTP requirement',
                },
            ],
            description: 'Finalize disabling OTP with confirmation code',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/transfer/id',
            method: 'GET',
            params: [
                {
                    parameter: 'id_or_code',
                    required: true,
                    type: 'String',
                    description: 'An ID or code for the transfer to retrieve',
                },
            ],
            description: 'Fetch transfer details by ID or code',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/transfer/id_or_code',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'List all bulk charge batches',
        },
        {
            api: 'resend',
            endpoint: 'https://api.paystack.co/transfer/resend_otp',
            method: 'POST',
            params: [
                {
                    parameter: 'transfer_code',
                    required: true,
                    type: 'String',
                    description: 'Transfer code',
                },
                {
                    parameter: 'reason',
                    required: true,
                    type: 'String',
                    description: 'Either "resend_otp" or "transfer"',
                },
            ],
            description: 'Resend OTP for a transfer',
        },
    ],
    paymentrequest: [
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/paymentrequest',
            method: 'POST',
            params: [
                {
                    parameter: 'customer',
                    required: true,
                    type: 'String',
                    description: 'Customer ID or code',
                },
                {
                    parameter: 'due_date',
                    required: true,
                    type: 'String',
                    description: 'ISO 8601 representation of request due date',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Invoice amount in kobo',
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Description of the payment request',
                },
                {
                    parameter: 'line_items',
                    required: false,
                    type: 'String',
                    description: 'Array of line items',
                },
                {
                    parameter: 'tax',
                    required: false,
                    type: 'String',
                    description: 'Array of taxes to be charged',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency (defaults to NGN)',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'send_notification',
                    required: false,
                    type: 'String',
                    description: 'Whether to send email notification (defaults to true)',
                },
                {
                    parameter: 'draft',
                    required: false,
                    type: 'String',
                    description: 'Save as draft (defaults to false)',
                },
                {
                    parameter: 'has_invoice',
                    required: false,
                    type: 'String',
                    description: 'Create a draft invoice even without line items or tax',
                },
                {
                    parameter: 'invoice_number',
                    required: false,
                    type: 'String',
                    description: 'Override the auto-incrementing invoice number',
                },
            ],
            description: 'Create a new payment request',
        },
        {
            api: 'finalize',
            endpoint: 'https://api.paystack.co/paymentrequest/finalize/ID_OR_CODE',
            method: 'POST',
            params: [
                {
                    parameter: 'send_notification',
                    required: false,
                    type: 'String',
                    description: 'Whether to send email notification (defaults to true)',
                },
            ],
            description: 'Finalize/publish a draft payment request',
        },
        {
            api: 'send',
            endpoint: 'https://api.paystack.co/paymentrequest/notify/ID_OR_CODE',
            method: 'POST',
            params: [],
            description: 'Send payment request notification to customer',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/paymentrequest',
            method: 'GET',
            params: [
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Filter by customer ID',
                },
                {
                    parameter: 'status',
                    required: false,
                    type: 'String',
                    description: 'Filter by status: "failed", "success", or "abandoned"',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Filter by currency',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'paid',
                    required: false,
                    type: 'String',
                    description: 'Filter requests that have been paid for',
                },
                {
                    parameter: 'include_archive',
                    required: false,
                    type: 'String',
                    description: 'Include archived payment requests',
                },
                {
                    parameter: 'payment_request',
                    required: false,
                    type: 'String',
                    description: 'Filter by invoice code',
                },
            ],
            description: 'List all payment requests',
        },
        {
            api: 'view',
            endpoint: 'https://api.paystack.co/paymentrequest/REQUEST_ID_OR_CODE',
            method: 'GET',
            params: [
                {
                    parameter: 'id',
                    required: true,
                    type: 'String',
                    description: 'Payment request ID or code',
                },
            ],
            description: 'View a specific payment request',
        },
        {
            api: 'invoice',
            endpoint: 'https://api.paystack.co/paymentrequest/totals',
            method: 'GET',
            params: [],
            description: 'Get payment request totals',
        },
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/paymentrequest/ID_OR_CODE',
            method: 'PUT',
            params: [
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Payment request description',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount in kobo',
                },
                {
                    parameter: 'line_item',
                    required: false,
                    type: 'String',
                    description: 'Line items',
                },
                {
                    parameter: 'tax',
                    required: false,
                    type: 'String',
                    description: 'Taxes',
                },
                {
                    parameter: 'due_date',
                    required: false,
                    type: 'String',
                    description: 'Due date for the request',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional metadata',
                },
                {
                    parameter: 'send_notification',
                    required: false,
                    type: 'String',
                    description: 'Whether to send notification',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency (only works in draft mode)',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Customer ID (only works in draft mode)',
                },
            ],
            description: 'Update a payment request',
        },
        {
            api: 'verify',
            endpoint: 'https://api.paystack.co/paymentrequest/verify/{id}',
            method: 'GET',
            params: [
                {
                    parameter: 'id',
                    required: false,
                    type: 'String',
                    description: 'The invoice code for the Payment Request to be verified',
                    paramType: 'path',
                },
            ],
            description: 'Verify details of a payment request on your integration.',
        },
    ],
    transferrecipient: [
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/transferrecipient',
            method: 'POST',
            params: [
                {
                    parameter: 'type',
                    required: true,
                    type: 'String',
                    description: 'Recipient Type',
                    options: ['nuban', 'ghipss', 'mobile_money', 'basa']
                },
                {
                    parameter: 'name',
                    required: true,
                    type: 'String',
                    description: 'A name for the recipient',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional information in structured JSON format',
                },
                {
                    parameter: 'bank_code',
                    required: true,
                    type: 'String',
                    description: 'Bank code from the List Banks endpoint',
                },
                {
                    parameter: 'account_number',
                    required: true,
                    type: 'String',
                    description: 'Bank account number (required if type is nuban)',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency for the account receiving the transfer',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Description for the recipient',
                },
            ],
            description: 'Create a new transfer recipient',
        },
        {
            api: 'delete',
            endpoint: 'https://api.paystack.co/transferrecipient/{id_or_code}',
            method: 'DELETE',
            params: [
                {
                    parameter: 'id_or_code',
                    required: true,
                    type: 'String',
                    description: 'Transfer Recipient\'s ID or code',
                    paramType: 'path',
                }
            ],
            description: 'Delete a transfer recipient',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/transferrecipient',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'List all transfer recipients',
        },
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/transferrecipient/{id_or_code}',
            method: 'PUT',
            params: [
                {
                    parameter: 'id_or_code',
                    required: true,
                    type: 'String',
                    description: 'Transfer Recipient\'s ID or code',
                    paramType: 'path',
                },
            ],
            description: 'Update a transfer recipient',
        },
    ],
    subscription: [
        {
            api: 'disable',
            endpoint: 'https://api.paystack.co/subscription/disable',
            method: 'POST',
            params: [
                {
                    parameter: 'code',
                    required: true,
                    type: 'String',
                    description: 'Subscription code',
                },
                {
                    parameter: 'token',
                    required: true,
                    type: 'String',
                    description: 'Email token',
                },
            ],
            description: 'Disable a subscription',
        },
        {
            api: 'fetch',
            endpoint: ':id_or_subscription_code',
            method: 'GET',
            params: [],
            description: 'Fetch a specific subscription',
        },
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/subscription',
            method: 'POST',
            params: [
                {
                    parameter: 'customer',
                    required: true,
                    type: 'String',
                    description: 'Customer email address or customer code',
                },
                {
                    parameter: 'plan',
                    required: true,
                    type: 'String',
                    description: 'Plan code',
                },
                {
                    parameter: 'authorization',
                    required: false,
                    type: 'String',
                    description: 'Authorization code (required if customer has multiple authorizations)',
                },
                {
                    parameter: 'start_date',
                    required: false,
                    type: 'String',
                    description: 'Start date for the first debit (ISO 8601 format)',
                },
            ],
            description: 'Create a subscription for a customer',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/subscription',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Filter by Customer ID',
                },
                {
                    parameter: 'plan',
                    required: false,
                    type: 'String',
                    description: 'Filter by Plan ID',
                },
            ],
            description: 'List all subscriptions',
        },
        {
            api: 'enable',
            endpoint: 'https://api.paystack.co/subscription/enable',
            method: 'POST',
            params: [
                {
                    parameter: 'code',
                    required: true,
                    type: 'String',
                    description: 'Subscription code',
                },
                {
                    parameter: 'token',
                    required: true,
                    type: 'String',
                    description: 'Email token',
                },
            ],
            description: 'Enable a subscription',
        },
    ],
    bulkcharge: [
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/bulkcharge/id_or_code',
            method: 'GET',
            params: [
                {
                    parameter: 'id_or_code',
                    required: true,
                    type: 'String',
                    description: 'An ID or code for the batch whose details you want to retrieve',
                },
            ],
            description: 'Fetch a specific bulk charge batch with progress information',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/bulkcharge/id_or_code/charges',
            method: 'GET',
            params: [
                {
                    parameter: 'id_or_code',
                    required: true,
                    type: 'String',
                    description: 'An ID or code for the batch whose charges you want to retrieve',
                },
                {
                    parameter: 'status',
                    required: false,
                    type: 'String',
                    description: 'Filter by status: "pending", "success", or "failed"',
                },
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'Retrieve all charges associated with a bulk charge batch',
        },
        {
            api: 'initiate',
            endpoint: 'https://api.paystack.co/bulkcharge',
            method: 'POST',
            params: [],
            description: 'Initiate a bulk charge by sending an array of authorization codes and amounts',
        },
        {
            api: 'resume',
            endpoint: 'https://api.paystack.co/bulkcharge/resume/batch_code',
            method: 'GET',
            params: [
                {
                    parameter: 'batch_code',
                    required: true,
                    type: 'String',
                    description: 'Code of the batch to resume processing',
                },
            ],
            description: 'Resume processing a paused bulk charge batch',
        },
        {
            api: 'pause',
            endpoint: 'https://api.paystack.co/bulkcharge/pause/batch_code',
            method: 'GET',
            params: [
                {
                    parameter: 'batch_code',
                    required: true,
                    type: 'String',
                    description: 'Code of the batch to pause',
                },
            ],
            description: 'Pause processing a bulk charge batch',
        },
    ],
    bank: [
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/bank',
            method: 'GET',
            params: [],
            description: 'List all supported banks',
        },
        {
            api: 'resolve',
            endpoint: 'https://api.paystack.co/bank/resolve?account_number={account_number}&bank_code={bank_code}',
            method: 'GET',
            params: [
                {
                    parameter: 'account_number',
                    required: true,
                    type: 'String',
                    description: 'Bank account number',
                    paramType: 'path',
                },
                {
                    parameter: 'bank_code',
                    required: true,
                    type: 'String',
                    description: 'Bank code',
                    paramType: 'path',
                },
            ],
            description: 'Resolve account details by account number and bank code',
        },
        // {
        //     api: 'resolve',
        //     endpoint: 'https://api.paystack.co/bank/resolve/{bvn}',
        //     method: 'GET',
        //     params: [
        //         {
        //             parameter: 'bvn',
        //             required: true,
        //             type: 'String',
        //             description: '11 digit BVN',
        //         },
        //     ],
        //     description: 'Resolve account details by BVN',
        // },
        {
            api: 'match',
            endpoint: '{account_number}&bank_code={bank_code}&bvn={bvn}',
            method: 'GET',
            params: [
                {
                    parameter: 'account_number',
                    required: true,
                    type: 'String',
                    description: 'Bank account number',
                    paramType: 'path',
                },
                {
                    parameter: 'bank_code',
                    required: true,
                    type: 'String',
                    description: 'Bank code from List Bank endpoint',
                    paramType: 'path',
                },
                {
                    parameter: 'bvn',
                    required: true,
                    type: 'String',
                    description: '11 digit BVN',
                    paramType: 'path',
                },
            ],
            description: 'Match account details with BVN for verification',
        },
    ],
    charge: [
        {
            api: 'submit',
            endpoint: 'https://api.paystack.co/charge/submit_otp',
            method: 'POST',
            params: [
                {
                    parameter: 'otp',
                    required: true,
                    type: 'String',
                    description: 'OTP submitted by user',
                },
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Reference for ongoing transaction',
                },
            ],
            description: 'Submit OTP to complete a charge',
        },
        {
            api: 'submit',
            endpoint: 'https://api.paystack.co/charge/submit_pin',
            method: 'POST',
            params: [
                {
                    parameter: 'pin',
                    required: true,
                    type: 'String',
                    description: 'PIN submitted by user',
                },
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Reference for transaction that requested PIN',
                },
            ],
            description: 'Submit PIN to complete a charge',
        },
        {
            api: 'submit',
            endpoint: 'https://api.paystack.co/charge/submit_birthday',
            method: 'POST',
            params: [
                {
                    parameter: 'birthday',
                    required: true,
                    type: 'String',
                    description: 'Birthday submitted by user',
                },
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Reference for ongoing transaction',
                },
            ],
            description: 'Submit birthday to complete a charge',
        },
        {
            api: 'tokenize',
            endpoint: 'https://api.paystack.co/charge/tokenize',
            method: 'POST',
            params: [
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'card',
                    required: true,
                    type: 'String',
                    description: 'Card object containing number, cvv, expiry_month, and expiry_year',
                },
            ],
            description: 'Tokenize a card for future charges',
        },
        {
            api: 'check',
            endpoint: 'https://api.paystack.co/charge/reference',
            method: 'GET',
            params: [
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'The reference to check',
                },
            ],
            description: 'Check the status of a charge transaction',
        },
        {
            api: 'charge',
            endpoint: 'https://api.paystack.co/charge',
            method: 'POST',
            params: [
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Amount in kobo',
                },
                {
                    parameter: 'card',
                    required: false,
                    type: 'String',
                    description: 'Card object with number, cvv, expiry_month, and expiry_year',
                },
                {
                    parameter: 'bank',
                    required: false,
                    type: 'String',
                    description: 'Bank object with code and account_number',
                },
                {
                    parameter: 'authorization_code',
                    required: false,
                    type: 'String',
                    description: 'Valid authorization code to charge',
                },
                {
                    parameter: 'pin',
                    required: false,
                    type: 'String',
                    description: '4-digit PIN for non-reusable authorization code',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'A JSON object for additional transaction data',
                },
            ],
            description: 'Charge a customer using card, bank account, or authorization code',
        },
        {
            api: 'submit',
            endpoint: 'https://api.paystack.co/charge/submit_phone',
            method: 'POST',
            params: [
                {
                    parameter: 'phone',
                    required: true,
                    type: 'String',
                    description: 'Phone number submitted by user',
                },
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Reference for ongoing transaction',
                },
            ],
            description: 'Submit phone number to complete a charge',
        },
    ],
    transaction: [
        {
            api: 'verify',
            endpoint: 'https://api.paystack.co/transaction/verify/{reference}',
            method: 'GET',
            params: [
                {
                    parameter: 'reference',
                    required: true,
                    type: 'String',
                    description: 'Transaction reference to verify',
                    paramType: 'path',
                },
            ],
            description: 'Verify transaction status by reference',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/transaction',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Specify an ID for the customer whose transactions you want to retrieve',
                },
                {
                    parameter: 'status',
                    required: false,
                    type: 'String',
                    description: 'Filter transactions by status ("failed", "success", "abandoned")',
                },
                {
                    parameter: 'from',
                    required: false,
                    type: 'String',
                    description: 'A timestamp from which to start listing transactions (e.g. 2016-09-24T00:00:05.000Z, 2016-09-21)',
                },
                {
                    parameter: 'to',
                    required: false,
                    type: 'String',
                    description: 'A timestamp at which to stop listing transactions (e.g. 2016-09-24T00:00:05.000Z, 2016-09-21)',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Filter transactions by amount (in kobo)',
                },
            ],
            description: 'List all transactions',
        },
        {
            api: 'view',
            endpoint: ':id_or_reference',
            method: 'GET',
            params: [],
            description: 'View a specific transaction',
        },
        {
            api: 'charge',
            endpoint: 'https://api.paystack.co/transaction/charge_authorization',
            method: 'POST',
            params: [
                {
                    parameter: 'authorization_code',
                    required: true,
                    type: 'String',
                    description: 'Valid authorization code to charge',
                },
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Amount in kobo',
                },
                {
                    parameter: 'reference',
                    required: false,
                    type: 'String',
                    description: 'Unique transaction reference',
                },
                {
                    parameter: 'plan',
                    required: false,
                    type: 'String',
                    description: 'Plan code for subscription',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency to charge in',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional transaction metadata',
                },
                {
                    parameter: 'subaccount',
                    required: false,
                    type: 'String',
                    description: 'Subaccount code that owns the payment',
                },
                {
                    parameter: 'transaction_charge',
                    required: false,
                    type: 'String',
                    description: 'Flat fee to charge the subaccount in kobo',
                },
                {
                    parameter: 'bearer',
                    required: false,
                    type: 'String',
                    description: 'Who bears Paystack charges: "account" or "subaccount"',
                },
                {
                    parameter: 'invoice_limit',
                    required: false,
                    type: 'String',
                    description: 'Number of invoices to raise during subscription',
                },
            ],
            description: 'Charge a customer using a stored authorization code',
        },
        {
            api: 'export',
            endpoint: 'https://api.paystack.co/transaction/export',
            method: 'GET',
            params: [
                {
                    arg: true,
                    parameter: 'from',
                    required: false,
                    type: 'String',
                    description: 'Lower bound of date range',
                },
                {
                    arg: true,
                    parameter: 'to',
                    required: false,
                    type: 'String',
                    description: 'Upper bound of date range',
                },
                {
                    parameter: 'settled',
                    required: false,
                    type: 'String',
                    description: 'Set to "true" for settled transactions or "false" for pending',
                },
                {
                    parameter: 'payment_page',
                    required: false,
                    type: 'String',
                    description: 'Payment page ID to filter transactions',
                },
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Customer ID to filter transactions',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency to filter transactions',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'settlement',
                    required: false,
                    type: 'String',
                    description: 'Settlement ID to filter transactions',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount to filter transactions',
                },
                {
                    parameter: 'status',
                    required: false,
                    type: 'String',
                    description: 'Status to filter transactions',
                },
            ],
            description: 'Export transactions to CSV',
        },
        {
            api: 'check',
            endpoint: 'https://api.paystack.co/transaction/check_authorization',
            method: 'POST',
            params: [
                {
                    parameter: 'authorization_code',
                    required: true,
                    type: 'String',
                    description: 'Authorization code for Mastercard or VISA',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Amount in kobo to check',
                },
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency for the amount to check',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
            ],
            description: 'Check if an authorization code has sufficient funds',
        },
        {
            api: 'transaction',
            endpoint: 'https://api.paystack.co/transaction/totals',
            method: 'GET',
            params: [
                {
                    arg: true,
                    parameter: 'from',
                    required: false,
                    type: 'String',
                    description: 'Lower bound of date range',
                },
                {
                    arg: true,
                    parameter: 'to',
                    required: false,
                    type: 'String',
                    description: 'Upper bound of date range',
                },
            ],
            description: 'Get total amount received on your account',
        },
        {
            api: 'initialize',
            endpoint: 'https://api.paystack.co/transaction/initialize',
            method: 'POST',
            params: [
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Amount in kobo',
                },
                {
                    parameter: 'reference',
                    required: false,
                    type: 'String',
                    description: 'Unique transaction reference or leave blank for auto-generation',
                },
                {
                    parameter: 'callback_url',
                    required: false,
                    type: 'String',
                    description: 'URL to redirect to after payment',
                },
                {
                    parameter: 'plan',
                    required: false,
                    type: 'String',
                    description: 'Plan code for subscription',
                },
                {
                    parameter: 'invoice_limit',
                    required: false,
                    type: 'String',
                    description: 'Number of invoices to raise during subscription',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional transaction metadata',
                },
                {
                    parameter: 'subaccount',
                    required: false,
                    type: 'String',
                    description: 'Subaccount code that owns the payment',
                },
                {
                    parameter: 'transaction_charge',
                    required: false,
                    type: 'String',
                    description: 'Flat fee to charge the subaccount in kobo',
                },
                {
                    parameter: 'bearer',
                    required: false,
                    type: 'String',
                    description: 'Who bears Paystack charges (defaults to "account")',
                },
                {
                    parameter: 'channels',
                    required: false,
                    type: 'String',
                    description: 'Payment channels to enable: "card", "bank", or both as array',
                },
            ],
            description: 'Initialize a transaction',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/transaction/id',
            method: 'GET',
            params: [
                {
                    parameter: 'id',
                    required: true,
                    type: 'String',
                    description: 'An ID for the transaction to fetch',
                },
            ],
            description: 'Fetch transaction details by ID',
        },
    ],
    plan: [
        {
            api: 'update',
            endpoint: ':id_or_plan_code',
            method: 'PUT',
            params: [
                {
                    parameter: 'name',
                    required: false,
                    type: 'String',
                    description: 'Name of plan',
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Short description of plan',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount to charge in kobo (will override amount for existing subscriptions)',
                },
                {
                    parameter: 'interval',
                    required: false,
                    type: 'String',
                    description: 'Billing interval (hourly, daily, weekly, monthly, annually)',
                },
                {
                    parameter: 'send_invoices',
                    required: false,
                    type: 'String',
                    description: 'Set to false to disable invoice emails',
                },
                {
                    parameter: 'send_sms',
                    required: false,
                    type: 'String',
                    description: 'Set to false to disable SMS notifications',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency for the amount',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'invoice_limit',
                    required: false,
                    type: 'String',
                    description: 'Number of invoices to raise during subscription (will not override active subscriptions)',
                },
            ],
            description: 'Update a plan',
        },
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/plan',
            method: 'POST',
            params: [
                {
                    parameter: 'name',
                    required: true,
                    type: 'String',
                    description: 'Name of plan',
                },
                {
                    parameter: 'description',
                    required: false,
                    type: 'String',
                    description: 'Short description of plan',
                },
                {
                    parameter: 'amount',
                    required: true,
                    type: 'Number',
                    description: 'Amount to charge in kobo',
                },
                {
                    parameter: 'interval',
                    required: true,
                    type: 'String',
                    description: 'Billing interval (hourly, daily, weekly, monthly, annually)',
                },
                {
                    parameter: 'send_invoices',
                    required: false,
                    type: 'String',
                    description: 'Set to false to disable invoice emails',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Currency for the amount',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'invoice_limit',
                    required: false,
                    type: 'String',
                    description: 'Number of invoices to raise during subscription',
                },
            ],
            description: 'Create a new plan',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/plan',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
                {
                    parameter: 'interval',
                    required: false,
                    type: 'String',
                    description: 'Filter list by plans with specified interval',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Filter list by plans with specified amount (in kobo)',
                },
            ],
            description: 'List all plans',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/plan/id_or_plan_code',
            method: 'GET',
            params: [],
            description: 'Fetch a specific plan',
        },
    ],
    customer: [
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/customer/:ID_OR_CUSTOMER_CODE',
            method: 'PUT',
            params: [
                {
                    parameter: 'first_name',
                    required: false,
                    type: 'String',
                    description: 'Customer first name',
                },
                {
                    parameter: 'last_name',
                    required: false,
                    type: 'String',
                    description: 'Customer last name',
                },
                {
                    parameter: 'phone',
                    required: false,
                    type: 'String',
                    description: 'Customer phone number',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional customer information in structured JSON format',
                },
            ],
            description: 'Update customer details',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/customer',
            method: 'GET',
            params: [
                {
                    parameter: 'perPage',
                    required: false,
                    type: 'String',
                    description: 'Specify how many records you want to retrieve per page',
                },
                {
                    parameter: 'page',
                    required: false,
                    type: 'Number',
                    description: 'Specify exactly what page you want to retrieve',
                },
            ],
            description: 'List all customers',
        },
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/customer',
            method: 'POST',
            params: [
                {
                    parameter: 'email',
                    required: true,
                    type: 'String',
                    description: 'Customer email address',
                },
                {
                    parameter: 'first_name',
                    required: false,
                    type: 'String',
                    description: 'Customer first name',
                },
                {
                    parameter: 'last_name',
                    required: false,
                    type: 'String',
                    description: 'Customer last name',
                },
                {
                    parameter: 'phone',
                    required: false,
                    type: 'String',
                    description: 'Customer phone number',
                },
                {
                    parameter: 'metadata',
                    required: false,
                    type: 'String',
                    description: 'Additional customer information in structured JSON format',
                },
            ],
            description: 'Create a new customer',
        },
        {
            api: 'fetch',
            endpoint: ':id_or_customer_code',
            method: 'GET',
            params: [
                {
                    parameter: 'exclude_transactions',
                    required: false,
                    type: 'String',
                    description: 'By default, fetching a customer returns all their transactions. Set this to true to disable this behaviour',
                },
            ],
            description: 'Fetch a specific customer',
        },
        {
            api: 'set_risk_action',
            endpoint: 'https://api.paystack.co/customer/set_risk_action',
            method: 'POST',
            params: [
                {
                    parameter: 'customer',
                    required: false,
                    type: 'String',
                    description: 'Customer ID, code, or email address',
                },
                {
                    parameter: 'risk_action',
                    required: false,
                    type: 'String',
                    description: 'One of the possible risk actions. "allow" to whitelist, "deny" to blacklist',
                },
            ],
            description: 'Set customer risk action (whitelist or blacklist)',
        },
        {
            api: 'deactivate',
            endpoint: 'https://api.paystack.co/customer/deactivate_authorization',
            method: 'POST',
            params: [
                {
                    parameter: 'authorization_code',
                    required: true,
                    type: 'String',
                    description: 'Authorization code to deactivate',
                },
            ],
            description: 'Deactivate an authorization for a customer',
        },
    ],
    refund: [
        {
            api: 'create',
            endpoint: 'https://api.paystack.co/refund',
            method: 'POST',
            params: [
                {
                    parameter: 'transaction',
                    required: true,
                    type: 'String',
                    description: 'Transaction reference or ID to refund',
                },
                {
                    parameter: 'amount',
                    required: false,
                    type: 'Number',
                    description: 'Amount to refund in kobo (defaults to full transaction amount)',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Three-letter ISO currency code',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
                {
                    parameter: 'customer_note',
                    required: false,
                    type: 'String',
                    description: 'Customer-facing reason for refund',
                },
                {
                    parameter: 'merchant_note',
                    required: false,
                    type: 'String',
                    description: 'Internal merchant reason for refund',
                },
            ],
            description: 'Create a refund for a transaction',
        },
        {
            api: 'fetch',
            endpoint: ':id',
            method: 'GET',
            params: [
                {
                    parameter: 'id',
                    required: false,
                    type: 'String',
                    description: 'ID of the refund to retrieve',
                },
            ],
            description: 'Fetch refund details by ID',
        },
        {
            api: 'list',
            endpoint: 'https://api.paystack.co/refund',
            method: 'GET',
            params: [
                {
                    parameter: 'transaction',
                    required: false,
                    type: 'String',
                    description: 'Filter by transaction',
                },
                {
                    parameter: 'currency',
                    required: false,
                    type: 'String',
                    description: 'Filter by currency',
                    options: ['NGN', 'GHS', 'ZAR', 'KES', 'UGX', 'TZS', 'XAF', 'XOF', 'USD'],
                },
            ],
            description: 'List all refunds',
        },
    ],
    integration: [
        {
            api: 'update',
            endpoint: 'https://api.paystack.co/integration/payment_session_timeout',
            method: 'PUT',
            params: [
                {
                    parameter: 'timeout',
                    required: false,
                    type: 'String',
                    description: 'Session timeout in seconds (set to 0 to disable session timeouts)',
                },
            ],
            description: 'Update payment session timeout setting',
        },
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/integration/payment_session_timeout',
            method: 'GET',
            params: [],
            description: 'Fetch payment session timeout setting',
        },
    ],
    balance: [
        {
            api: 'check',
            endpoint: 'https://api.paystack.co/balance',
            method: 'GET',
            params: [],
            description: 'You can only transfer from what you have',
        },
        {
            api: 'balance',
            endpoint: 'https://api.paystack.co/balance/ledger',
            method: 'GET',
            params: [],
            description: 'Retrieve account balance ledger activity',
        },
    ],
    settlement: [
        {
            api: 'fetch',
            endpoint: 'https://api.paystack.co/settlement',
            method: 'GET',
            params: [
                {
                    arg: true,
                    parameter: 'from',
                    required: false,
                    type: 'String',
                    description: 'Lower bound of date range. Leave undefined to export settlement from day one',
                },
                {
                    arg: true,
                    parameter: 'to',
                    required: false,
                    type: 'String',
                    description: 'Upper bound of date range. Leave undefined to export settlements till date',
                },
                {
                    parameter: 'subaccount',
                    required: false,
                    type: 'String',
                    description: 'Provide a subaccount code to export only settlements for that subaccount. Set to "none" to export only transactions for the account',
                },
            ],
            description: 'Retrieve settlements made to your bank accounts',
        },
    ],
    decision: [
        {
            api: 'resolve',
            endpoint: '{BIN)',
            method: 'GET',
            params: [
                {
                    parameter: 'bin',
                    required: true,
                    type: 'String',
                    description: 'First 6 characters of card',
                },
            ],
            description: 'Resolve card information by BIN',
        },
    ],
    invoice: [
        {
            api: 'archive',
            endpoint: ':id_or_code',
            method: 'POST',
            params: [],
            description: 'Archive an invoice to prevent it from being fetched or verified',
        },
    ],
    verifications: [
        {
            api: 'resolve',
            endpoint: 'https://api.paystack.co/verifications',
            method: 'POST',
            params: [
                {
                    parameter: 'verification_type',
                    required: true,
                    type: 'String',
                    description: 'Type of verification to perform',
                },
                {
                    parameter: 'phone',
                    required: true,
                    type: 'String',
                    description: 'Customer phone number with country code (no + prefix)',
                },
                {
                    parameter: 'callback_url',
                    required: false,
                    type: 'String',
                    description: 'URL to receive verification details',
                },
            ],
            description: 'Verify customer authenticity using Truecaller API',
        },
    ],
}


export default APIs